#define FPF_TAX1           1
#define FPB_TAXOP1         2
#define FPF_TAX2           3
#define FPB_TAXOP2         4
#define FPF_TAX3           5
#define FPB_TAXOP3         6
#define FPF_TAX4           7
#define FPB_TAXOP4         8
#define FPT_DATE           9
#define FPT_TIME           10
#define FPT_CASHIER        11
#define FPB_OPPARAM        12
#define FPB_TERMINAL       13
#define FPT_HEAD1          14
#define FPT_HEAD2          15
#define FPT_HEAD3          16
#define FPT_HEAD4          17
#define FPT_HEAD5          18
#define FPT_HEAD6          19
#define FPT_INFO1          20
#define FPT_INFO2          21
#define FPT_INFO3          22
#define FPT_INFO4          23
#define FPB_EMPTYLINES     24
#define FPB_CUTPLACE       25
#define FPB_LINEWIDTH      26
#define FPB_PERIPHERY      27
#define FPB_TIMEOUT        28
#define FPB_DRAWER         29
#define FPT_XTRANAME1      30
#define FPT_XTRANAME2      31
#define FPB_PORTSPEED      32
#define FPB_SHIFTRTEXT     33
#define FPT_PUBLICITY      34
#define FPB_PUBSPEED       35
#define FPT_XTARASUM       36
#define FPT_XTARAQTY       37
#define FPT_XTRANAME3      38
#define FPT_XTRANAME4      39
#define FPB_DECIMAL        40
#define FPT_PASWORD        41
#define FPT_MONEUNIT       42
#define FPT_CREDIT1        43
#define FPT_CREDIT2        44
#define FPT_CREDIT3        45
#define FPT_RECEIVED2      46
#define FPT_PAIDOUT2       47
#define FPF_EURRATE        48
#define FPB_EXTRPRM			49
#define FPF_MINUNIT        50
#define FPB_ESC1B33        51
#define FPT_CREDIT4			52
#define FPT_CREDIT5      	53
#define FPB_PRNDSP2			54
#define FPT_MONEUN2    		55
#define FPB_BASEUNT			56
#define FPT_PAIDOUT3       57
#define FPB_DSPTIPE        58
#define FPF_TAX5           59
#define FPT_XTRANAME5      60
#define FPT_XTRANAME6      61
#define FPT_XTRANAME7      62
#define FPB_PRNTIMEOUT     63
#define FPT_RECEIVED3      64
#define FPT_RECEIVED4      65
#define FPT_RECEIVED5      66
#define FPT_PAIDOUT4       67
#define FPT_PAIDOUT5       68
#define FPB_TAXCOUNT			69
#define FPB_RCPTIMEOUT		70
