# coding: utf-8

---
salesPoint:
  type: text
  instances:
  - font_name: Arial
    font_height: 34
    font_width: 14
    font_weight: 1000
    orientation: 270
    x: 900
    y: 100
imageLeft:
  type: image
  common:
    orientation: 270
  instances:
  - x: 50
    y: 132
imageTop:
  type: image
  instances:
  - x: 325
    y: 26
imageBottom:
  type: image
  instances:
  - x: 325
    y: 510
eventName1:
  type: text
  instances:
  - font_name: Arial
    font_height: 34
    font_width: 14
    font_weight: 1000
    x: 325
    y: 137
eventName2:
  type: text
  instances:
  - font_name: Arial
    font_height: 34
    font_width: 14
    font_weight: 1000
    x: 325
    y: 174
eventLocation:
  type: text
  instances:
  - font_name: Arial
    font_height: 30
    font_width: 12
    font_weight: 1000
    x: 325
    y: 211
eventDateTime:
  type: text
  instances:
  - font_name: Arial
    font_height: 30
    font_width: 12
    font_weight: 1000
    x: 325
    y: 243
section1:
  type: text
  instances:
  - font_name: Arial
    font_height: 30
    font_width: 12
    font_weight: 1000
    x: 110
    y: 382
row1:
  type: text
  instances:
  - font_name: Arial
    font_height: 30
    font_width: 12
    font_weight: 1000
    x: 110
    y: 410
seat1:
  type: text
  instances:
  - font_name: Arial
    font_height: 30
    font_width: 12
    font_weight: 1000
    x: 110
    y: 438
priceGroup1:
  type: text
  instances:
  - font_name: Arial
    font_height: 30
    font_width: 12
    font_weight: 1000
    x: 325
    y: 410
section2:
  type: text
  instances:
  - font_name: Arial
    font_height: 25
    font_width: 10
    font_weight: 500
    x: 1035
    y: 236
row2:
  type: text
  instances:
  - font_name: Arial
    font_height: 25
    font_width: 10
    font_weight: 500
    x: 1035
    y: 261
seat2:
  type: text
  instances:
  - font_name: Arial
    font_height: 25
    font_width: 10
    font_weight: 500
    x: 1035
    y: 286
priceGroup2:
  type: text
  instances:
  - font_name: Arial
    font_height: 25
    font_width: 10
    font_weight: 500
    x: 1035
    y: 311
ticketPrice:
  type: text
  instances:
  - font_name: Arial
    font_height: 30
    font_width: 12
    font_weight: 1000
    x: 325
    y: 438
  - font_name: Arial
    font_height: 25
    font_width: 10
    font_weight: 500
    x: 1035
    y: 336
serviceFee:
  type: text
  instances:
  - font_name: Arial
    font_height: 22
    font_width: 8
    font_weight: 500
    x: 485
    y: 444
extraFee:
  type: text
  instances:
  - font_name: Arial
    font_height: 25
    font_width: 10
    font_weight: 700
    prefix: 'Плата за обслуживание в зале '
    suffix: " руб"
    x: 485
    y: 472
totalText:
  type: text
  instances:
  - font_name: Arial
    font_height: 30
    font_width: 12
    font_weight: 1000
    x: 825
    y: 438
totalPrice:
  type: text
  instances:
  - font_name: Arial
    font_height: 30
    font_width: 12
    font_weight: 1000
    x: 825
    y: 466
ticketId:
  type: text
  common:
    prefix: 'ID: '
    font_name: Arial
    font_height: 25
    font_width: 10
    font_weight: 500
  instances:
  - x: 110
    y: 100
  - x: 1035
    y: 100
  - x: 800
    y: 386
  - x: 1035
    y: 386
infoText1:
  type: text
  instances:
  - font_name: Arial
    font_height: 25
    font_width: 10
    font_weight: 500
    x: 325
    y: 105
infoText2:
  type: text
  instances:
  - font_name: Arial
    font_height: 25
    font_width: 10
    font_weight: 500
    x: 325
    y: 280
infoText3:
  type: text
  instances:
  - font_name: Arial
    font_height: 25
    font_width: 10
    font_weight: 500
    x: 325
    y: 305
infoText4:
  type: text
  instances:
  - font_name: Arial
    font_height: 25
    font_width: 10
    font_weight: 500
    x: 325
    y: 330
infoText5:
  type: text
  instances:
  - font_name: Arial
    font_height: 25
    font_width: 10
    font_weight: 500
    x: 325
    y: 355
ticketBarCode:
  type: code128
  common:
    thickness: 10
    width: 530
    height: 60
    orientation: 270
    quietzone: true
  instances:
  - x: 960
    y: 60
