import System
from System import *
oo=Type.GetTypeFromProgID("POS.SA97")
bills=Activator.CreateInstance(oo)
bills.Init("COM3",57600,15)
bills.FCancel()
bills.Print("Text Text Text Text Text Text Text Text")
bills.Print("Text Text Text Text Text Text Text Text")
bills.Print("Text Text Text Text Text Text Text Text")
bills.Print("Text Text Text Text Text Text Text Text")
bills.Print("Text Text Text Text Text Text Text Text")
bills.Print("Text Text Text Text Text Text Text Text")
bills.Print("Text Text Text Text Text Text Text Text")
bills.Print("Text Text Text Text Text Text Text Text")
bills.Print("----------------------------------------------------")
bills.NFOperation("1. Prekė   1234567890",20.0,65)
bills.NFOperation("2. Prekė   1234567890",20.0,65)
bills.NFOperation("3. Prekė   1234567890",20.0,65)
bills.Print("----------------------------------------------------")
bills.Print("Text Text Text Text Text Text Text Text")
bills.Print("Text Text Text Text Text Text Text Text")
bills.Print("Text Text Text Text Text Text Text Text")
bills.Print("----------------------------------------------------")
bills.NFFinish()
bills.Close()
